name: Release

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  release:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    name: Release on ${{ github.ref_name }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    env:
      NODE_VERSION: 20
      PNPM_VERSION: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Verify pnpm version
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Set branch-specific variables
        run: |
          BRANCH="${{ github.ref_name }}"
          case "$BRANCH" in
            dev)
              echo "PRERELEASE_FLAG=--prerelease" >> "$GITHUB_ENV"
              echo "RELEASE_TITLE_PREFIX=[DEV] " >> "$GITHUB_ENV"
              echo "VERSION_PREFIX=beta" >> "$GITHUB_ENV"
              ;;
            staging)
              echo "PRERELEASE_FLAG=--prerelease" >> "$GITHUB_ENV"
              echo "RELEASE_TITLE_PREFIX=[STAGING] " >> "$GITHUB_ENV"
              echo "VERSION_PREFIX=rc" >> "$GITHUB_ENV"
              ;;
            main)
              echo "PRERELEASE_FLAG=" >> "$GITHUB_ENV"
              echo "RELEASE_TITLE_PREFIX=Release " >> "$GITHUB_ENV"
              echo "VERSION_PREFIX=" >> "$GITHUB_ENV"
              ;;
            *)
              echo "Branch $BRANCH is not supported for release." && exit 1
              ;;
          esac

      - name: Get current version from package.json
        id: package_version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_ENV"

      - name: Get latest tag for branch
        id: get_latest_tag
        run: |
          BRANCH="${{ github.ref_name }}"
          PACKAGE_VERSION=$PACKAGE_VERSION

          # Get the base version without any pre-release identifiers
          BASE_VERSION=$PACKAGE_VERSION

          # Try to get the latest tag for this branch pattern
          if [[ "$BRANCH" == "dev" ]]; then
            # Find latest beta tag with this base version
            LATEST_TAG=$(git tag -l "v${BASE_VERSION}-beta.*" | sort -V | tail -n 1 || echo "")
            if [[ -z "$LATEST_TAG" ]]; then
              # No beta tag exists for this version, create first one
              NEW_TAG="v${BASE_VERSION}-beta.0"
            else
              # Extract the beta number and increment it
              BETA_NUM=$(echo $LATEST_TAG | sed -E 's/.*beta\.([0-9]+)$/\1/')
              BETA_NUM=$((BETA_NUM + 1))
              NEW_TAG="v${BASE_VERSION}-beta.${BETA_NUM}"
            fi
          elif [[ "$BRANCH" == "staging" ]]; then
            # Find latest rc tag with this base version
            LATEST_TAG=$(git tag -l "v${BASE_VERSION}-rc.*" | sort -V | tail -n 1 || echo "")
            if [[ -z "$LATEST_TAG" ]]; then
              # No rc tag exists for this version, create first one
              NEW_TAG="v${BASE_VERSION}-rc.0"
            else
              # Extract the rc number and increment it
              RC_NUM=$(echo $LATEST_TAG | sed -E 's/.*rc\.([0-9]+)$/\1/')
              RC_NUM=$((RC_NUM + 1))
              NEW_TAG="v${BASE_VERSION}-rc.${RC_NUM}"
            fi
          elif [[ "$BRANCH" == "main" ]]; then
            # Check if the exact version tag already exists
            EXACT_VERSION_TAG=$(git tag -l "v${BASE_VERSION}" | head -n 1 || echo "")
            if [[ -n "$EXACT_VERSION_TAG" ]]; then
              # Version tag already exists, we need to increment the patch version
              MAJOR=$(echo $BASE_VERSION | cut -d. -f1)
              MINOR=$(echo $BASE_VERSION | cut -d. -f2)
              PATCH=$(echo $BASE_VERSION | cut -d. -f3)
              PATCH=$((PATCH + 1))
              NEW_TAG="v$MAJOR.$MINOR.$PATCH"
              echo "Warning: Version v${BASE_VERSION} already exists as a tag. Incrementing to $NEW_TAG"
            else
              # Use the exact version from package.json
              NEW_TAG="v${BASE_VERSION}"
            fi
          fi

          echo "NEW_TAG=$NEW_TAG" >> "$GITHUB_ENV"
          echo "Generated new tag: $NEW_TAG"

      - name: Create and push git tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Generate and create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$NEW_TAG" --generate-notes $PRERELEASE_FLAG --title "$RELEASE_TITLE_PREFIX$NEW_TAG"

      - name: Start next development cycle on dev
        if: github.ref_name == 'main'
        run: |
          git fetch origin
          git checkout -b dev origin/dev

          # Get the base version from package.json
          DEV_PACKAGE_VERSION=$(node -p "require('./package.json').version")

          # Check if a beta tag already exists for this version
          EXISTING_BETA_TAG=$(git tag -l "v${DEV_PACKAGE_VERSION}-beta.*" | sort -V | tail -n 1 || echo "")

          if [[ -z "$EXISTING_BETA_TAG" ]]; then
            # No beta tag exists for this version, create first one
            NEXT_BETA_TAG="v${DEV_PACKAGE_VERSION}-beta.0"
          else
            # Extract the beta number and increment it
            BETA_NUM=$(echo $EXISTING_BETA_TAG | sed -E 's/.*beta\.([0-9]+)$/\1/')
            BETA_NUM=$((BETA_NUM + 1))
            NEXT_BETA_TAG="v${DEV_PACKAGE_VERSION}-beta.${BETA_NUM}"
          fi

          git tag $NEXT_BETA_TAG
          git push origin $NEXT_BETA_TAG

          echo "Created new development tag: $NEXT_BETA_TAG"
